deploy:
  stage: deploy
  only:
    - triggers
  needs:
    - pipeline: "7778"
      job: build
      artifacts: true
#    - pipeline: $PARENT_PIPELINE_ID
  tags:
    - docker
    - rcedit
  before_script:
    - apt-get update -qq || true
    - apt-get install git make python3 python3-venv pandoc -yy
    - python3 -m venv .
    - . ./bin/activate
    - pip3 install -r requirements.txt
  script:
    - . ./bin/activate
    - make
