deploy:
  stage: deploy
  only:
    - triggers
#  needs:
#    - pipeline: $PARENT_PIPELINE_ID
#      job: $PARENT_PIPELINE_JOB
#      artifacts: false # workaround for bug, see https://gitlab.com/gitlab-org/gitlab/-/issues/367229
  tags:
    - docker
    - rcedit
  script:
    # prepare environment
    - apt-get update -qq || true
    - apt-get install git make python3 python3-venv pandoc curl unzip -yy
    - python3 -m venv .
    - . ./bin/activate
    - pip3 install -r requirements.txt
    # fetch artifacts
    - ZIPFILE=$(mktemp -t artifactXXXXX)
    - ARTIFACT_DIR=$(mktemp -d -t artifactXXXXX)
    - curl --location --output $ZIPFILE --header "JOB-TOKEN:$CI_JOB_TOKEN" "https://gitlab.grrrr.org/api/v4/projects/$PARENT_PROJECT_ID/jobs/artifacts/$PARENT_PROJECT_REF/download?job=$PARENT_PIPELINE_JOB"
    - unzip $ZIPFILE -d $ARTIFACT_DIR || cat $ZIPFILE
    # transfer to RC
    - make DST=$ARTIFACT_DIR
